# Secret to store MongoDB credentials
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: admin
  password: password123  # Replace with something strong in real use ALSO this automatically ENCODE krta hai
